### ISSUE TITLE
include_ember_script_tags path wrong in Rspec integration tests

### ISSUE THREAD

**Issue by jboler** [thoughtbot/ember-cli-rails#186] opened 2015-07-24 21:13 UTC
I have Rspec configured to run some tests using selenium chrome webdriver. 

If I run just that file with `rspec spec/features/frontend_spec.rb` chrome boots up and all the tests pass. The paths generated by `include_ember_script_tags :frontend` are correct:

````
<script src="/assets/frontend/vendor.js"></script>
<script src="/assets/frontend/frontend.js"></script>
````

If I run my whole test suite including frontend_spec.rb then chrome boots up when it gets to the integration tests but the paths to the ember-cli code are wrong so nothing works:

````
<script src="/javascripts/frontend/vendor.js"></script>
<script src="/javascripts/frontend/frontend.js"></script>
````

My application.html.haml contains:

````
= include_ember_script_tags :frontend
````

Is this an RSpec issue or an ember-cli-rails issue? Any pointers in where to start?

**Comment by hesham** [comment] 2015-08-07 16:40
I'm not sure if this is related, but I had the same issue when I set the ember app's path in config/initializers/ember.rb to `Rails.root.join('frontend').to_s`. When I removed the path option, everything worked fine.

**Comment by jboler** [comment] 2015-08-08 03:19
I tried removing the path option from config/initializers/ember.rb but I still have the same problem:

```
   1) Workspace User toggles functions key
      Failure/Error: Unable to find matching line from backtrace
      ActionController::RoutingError:
        No route matches [GET] "/javascripts/frontend/vendor.js"
```

**Comment by dgalarza** [comment] 2015-08-11 15:49
I'm running into the same issue as well, no explicit path being set.

**Comment by seanpdoyle** [comment] 2015-11-03 13:48
@jboler @hesham was this ever resolved?

I have a hunch that those paths are correct, but the files that would be served by them (i.e. the Ember assets) are not being compiled/built before your test's request completes.

What what you [configured your `build_timeout`](https://github.com/thoughtbot/ember-cli-rails#options) to?

If this is still an issue, could you re-try your tests with a higher `build_timeout` value?

**Comment by seanpdoyle** [comment] 2015-11-03 13:49
Closing this issue due to its age and my [guess at the solution](https://github.com/thoughtbot/ember-cli-rails/issues/186#issuecomment-153357554).

If this ends up being incorrect, please ping me on this issue and I'll gladly re-open it.

**Comment by jboler** [comment] 2015-11-03 14:35
@seanpdoyle The issue still exists. My build_timeout is set to 90 seconds.

**Comment by seanpdoyle** [comment] 2015-11-03 14:43
@jboler what version of the gem are you using?

Could you try with the latest [0.4.1](https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.4.1)

**Comment by jboler** [comment] 2015-11-03 15:23
@seanpdoyle Still getting `No route matches [GET] "/javascripts/frontend/frontend.js"` on 0.4.1.

**Comment by jboler** [comment] 2015-11-03 15:26
@seanpdoyle FYI we switched from Selenium/Chromedriver to Poltergeist/PhantomJS and the error is still the same.

**Comment by seanpdoyle** [comment] 2015-11-03 15:27
Could you take a look at `log/development.log` and `log/test.log`?

Are there any build errors?

Have you configured your app with an [`enabled` lambda](https://github.com/thoughtbot/ember-cli-rails#options)? If so, are the paths you're exercising in your tests enabled via that block?

**Comment by jboler** [comment] 2015-11-03 15:48
No build errors. The correctly built files are present at `/assets/frontend/*.js` if I use Selenium/Chromedriver, put a long sleep in a JS spec then manually visit the JS paths in the browser. It's just the paths generated by `include_ember_script_tags` are incorrect.

No use of enabled lambda.

**Comment by seanpdoyle** [comment] 2015-11-03 16:04
This sounds like an Asset Pipeline / Sprockets issue.

[Our helpers](https://github.com/thoughtbot/ember-cli-rails/blob/ef0fc67958877c5ae37e4f1b78576c7a37e7cdac/app/helpers/ember_rails_helper.rb#L18-L24) end up invoking [something equivalent to](https://github.com/thoughtbot/ember-cli-rails/blob/ef0fc67958877c5ae37e4f1b78576c7a37e7cdac/lib/ember-cli/app.rb#L86-L97):

```rb
javascript_include_tag "frontend/frontend.js", "frontend/vendor.js"
```

We don't do anything else in terms of asset path resolution.

What is the value of `ENV["RAILS_ENV"]` at the time of test invocation? I think Sprockets will resolve assets as `/javascript/*.js` in one case and `/assets/*.js` in another.

**Comment by jboler** [comment] 2015-11-04 17:11
`ENV["RAILS_ENV"]` is set to `test` when I log that from within a test. This is the case whether running just the JS specs (producing the correct JS paths) or running all the specs (producing the wrong JS paths).

**Comment by seanpdoyle** [comment] 2015-11-19 00:53
@jboler Hey there, sorry this has gone silent.

There's been a lot of movement on this repo recently.

Could you try this again for version [0.5.3](https://rubygems.org/gems/ember-cli-rails/versions/0.5.3)?

**Comment by blmundie** [comment] 2015-11-20 21:13
From what I can tell while the initial build is happening the link shows up as /javascript/*.js.  Once the build is done it shows up as /assets/*.js

**Comment by seanpdoyle** [comment] 2015-11-20 21:18
@jboler @blmundie would either of you be able to share the repositories you're seeing this issue on?

If not, do you think you could distill the problem code into a repository so that I can work on reproducing it?

**Comment by jboler** [comment] 2015-11-20 21:32
I will try to create a minimal repo which can reproduce this.

**Comment by seanpdoyle** [comment] 2015-12-03 23:55
@jboler any movement on this?

**Comment by seanpdoyle** [comment] 2015-12-05 15:22
@jboler would you mind trying out [the latest release](https://github.com/thoughtbot/ember-cli-rails/releases/latest)?

**Comment by jboler** [comment] 2015-12-07 04:28
With the latest release `rspec -t js` now fails where it used to work. Here's the error, I think the path is wrong because the same broken path is being generated by `include_ember_script_tags :frontend` even when accessing the app in development mode from a browser.
```
No route matches [GET] "/javascripts/frontend/assets/frontend.js"
```

**Comment by seanpdoyle** [comment] 2015-12-07 05:20
@jboler thanks for the update!

How are you serving the ember app? 

Have you followed the [instructions for configuring the controller](https://github.com/thoughtbot/ember-cli-rails#configuring-the-ember-controller)?

**Comment by jboler** [comment] 2015-12-08 23:13
We're not using the Ember index.html. We have a regular Rails app with normal layouts/views so we're just using
```
<%= include_ember_script_tags :frontend %>
```
Is there any other configuration that's necessary?

**Comment by seanpdoyle** [comment] 2015-12-10 01:01
@jboler  would you mind trying out:

* https://github.com/thoughtbot/ember-cli-rails/tree/remove-sprockets for `ember-cli-rails` gem
* https://github.com/rondale-sc/ember-cli-rails-addon/tree/remove-sprockets for `ember-cli-rails-addon`

Each of those branches has up-to-date README's.

**Comment by seanpdoyle** [comment] 2015-12-10 04:16
I'm hopeful that we can get this fix landed and stabilize things for you.

Having said that, we don't plan on supporting the `include_ember_*_tags` helpers in post-`1.0.0` versions of this gem.

It is likely they'll be extracted to a stable gem, but I highly recommend you migrate toward using the `render_ember_app` helper, which relies 100% on EmberCLI to generate the page's HTML.

**Comment by seanpdoyle** [comment] 2015-12-10 15:26
@sevab would you mind trying out https://github.com/thoughtbot/ember-cli-rails/pull/347?

It removes the need for the consumer (you) to manually invoke `EmberCli.build`.

**Comment by seanpdoyle** [comment] 2015-12-11 21:17
@jboler [`0.6.0` has landed](https://github.com/thoughtbot/ember-cli-rails/releases/tag/v0.6.0) and removes all sprockets integration.

I'm closing this issue. 

Please try out the new version.

**Closed by seanpdoyle** 2015-12-11 21:17 UTC
Labels: bug
