### ISSUE TITLE
ArgumentError: Malformed version number string ^0.2.3

### ISSUE THREAD

**Issue by jeradg** [thoughtbot/ember-cli-rails#152] opened 2015-04-14 15:27 UTC
Using ember-cli-rails 0.3.1 with ember-cli 0.2.3, Rails 4.2.1 and Ruby 2.2.1.

I just upgraded ember-cli to version 0.2.3. In doing so, I changed the version range for ember-cli in my package.json to "^0.2.3", which is valid notation. However, when I run `rails s` to start my server, ember-cli-rails fails to build, producing an ArgumentError:

> Malformed version number string ^0.2.3

Changing the version in package.json to just "0.2.3" causes the app to build successfully.

The error seems to come from the `match_version?` method in lib/ember-cli/helpers.rb. Starting on line 5:

```ruby
def match_version?(version, requirements)
  version = Gem::Version.new(version)
# ...
```

Basically, `match_version?` uses RubyGems' `Gem::Version.new(version)`, which only accepts a string of the form "x.x.x", where "x" is a digit (or digits).

So the problem in short:

- `Gem::Version::new` only accepts version numbers of the form "x.x.x".
- package.json allows version ranges that can include characters like "^".
- `match_version?` assumes that you've declared a specific version of ember-cli in your package.json, rather than a version range, and naively passes that string to `Gem::Version::new`.

This suggests a few options for a solution:

- Don't change the code, and specify in the ember-cli-rails docs that you must declare a specific version of ember-cli in package.json.
- Strip any symbols aside from "." from the version number. However, this doesn't take into account that a) the resulting version number might not match the version actually installed ("^0.2.1" could result in 0.2.3 being installed), and b) version ranges like `"qux" : "<1.0.0 || >=2.3.1 <2.4.5 || >=2.5.2 <3.0.0"` are valid in package.json files.
- Check what version of ember-cli is *actually installed* and use that version number. A naive way of doing this would be to open node_modules/ember-cli/package.json to see what version is declared. Since this is (almost?) guaranteed to be the relative location of ember-cli's package.json file, this might be the way to go, with parsing the app's package.json as a backup if ember-cli's can't be found.

Happy to submit a pull request.

**Comment by joshpfosi** [comment] 2015-07-26 12:37
I am experiencing this same issue and agree with potential solutions.

**Comment by jeradg** [comment] 2015-07-27 19:11
@rwz: Any thoughts on this? I'm happy to submit a PR if the proposed solution (the third option) makes sense to you.

**Comment by rwz** [comment] 2015-07-27 19:34
The problem is not `Gem::Version` per se, it's this code:

```ruby
requirement = Gem::Requirement.new(requirement)
requirement.satisfied_by?(version)
```

So, Gem::Requirements expects Gemfile-like requirement specification, sort of like "~> 0.3.1". NPM's version specifications are different and I was too lazy to account for that.

The easiest thing would be to do nothing and add some readme suggesting using the most straigtforward version constraint format like "x.x.x". Or add some code to catch the error and print this suggestion as an error message.

I'd suggest against trying to parse NPM version constraint manually, since it'll probably be brittle and clunky.

**Comment by seanpdoyle** [comment] 2015-10-23 19:03
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, and @rwz latest comment doesn't properly address it, please comment on this issue and we'll reopen.

Thanks for your patience.

**Closed by seanpdoyle** 2015-10-23 19:03 UTC
