### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat 

### ISSUE THREAD

**Issue by fullofcaffeine** [thoughtbot/ember-cli-rails#195] opened 2015-08-05 22:05 UTC
Whenever I add or change the name of a file under the EmberJS app folder (in my case `RAILS_ROOT/frontend`) and I refresh the Rails app, I get the following error:

```j
Error: ENOENT: no such file or directory, lstat 'frontend/tmp/config_loader-cache_path-hbItGQ0V.tmp'
    at Error (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at symlink (frontend/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26)
    at Function.symlinkOrCopySync (frontend/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at frontend/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:102:19
    at lib$rsvp$$internal$$tryCatch (frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:408:9)
```

I'm using `ember-cli-rails` v0.3.5, `Ruby` v2.2.1p85, `io.js` v2.5.0, `npm` v2.13.12 and `ember-cli` v. 1.13.6. The other npm libs I'm using: http://pastiebin.com/55c2883325c1d.

Any ideas on why this happens?

Thanks!

**Comment by seanpdoyle** [comment] 2015-10-23 18:47
Thanks for bringing this to our attention.

This sounds like a duplicate of https://github.com/thoughtbot/ember-cli-rails/issues/94, so I'm closing it

Are you running Unicorn, Puma, or another multi process application server? If so, please checkout the [Multi-process server section of the README.](https://github.com/thoughtbot/ember-cli-rails#serving-from-multi-process-servers-in-development)

If you think this is another issue entirely, please let us know and we'll reopen this issue.

**Closed by seanpdoyle** 2015-10-23 18:47 UTC
