### ISSUE TITLE
How to enable code reload in development

### ISSUE THREAD

**Issue by begin29** [thoughtbot/ember-cli-rails#169] opened 2015-06-04 08:11 UTC
Sometimes code isn't reloaded after some changing. How always enable code reloading?

**Comment by jeffreybiles** [comment] 2015-06-06 03:00
I'm having this problem too.  I have to restart my rails server to get the code to reload, which I don't believe is the intended behavior.

**Comment by jeffreybiles** [comment] 2015-06-06 03:13
I recently had this problem- was having to restart Rails on each code change.  Restarting both iTerm and sublime text fixed it for me...  I suspect the watcher got overloaded.

**Comment by jeffreybiles** [comment] 2015-06-06 16:25
(Note: this only fixes it for a couple hours.  A better solution would be wonderful)

**Comment by seanpdoyle** [comment] 2015-10-23 18:58
This should not be happening. 

What application server are you running?

Is it multi-process? If so, please read the [multi-process server](https://github.com/thoughtbot/ember-cli-rails#serving-from-multi-process-servers-in-development) section of the README.

**Comment by seanpdoyle** [comment] 2015-11-02 03:20
@begin29 @jeffreybiles could you provide some more information about the failures you were seeing, in addition to https://github.com/thoughtbot/ember-cli-rails/issues/169#issuecomment-150663616?

What types of files were you changing? Were they implementation files or configuration files?

Are you using [Spring](https://github.com/rails/spring)? 

Are you not seeing updates for EmberCLI files? For Rails files? For both?

**Comment by jeffreybiles** [comment] 2015-11-02 15:30
Hey, it's been a while since this happened.  Problem has resolved since switching from Sublime Text to Atom.  Sorry I don't recall more specific info.

**Comment by seanpdoyle** [comment] 2015-11-02 15:40
@jeffreybiles sounds good.

@begin29 I'm closing this issue.

Please let me know if there's still a problem and I'll reopen.

**Closed by seanpdoyle** 2015-11-02 15:40 UTC

**Comment by Tonkpils** [comment] 2016-04-03 16:07
I'm running into this issue, making changes to my rails code does not get updated on the next request. 

I'm using Rails v5.0.0.beta3 and Spring
