### ISSUE TITLE
rails 5 support?

### ISSUE THREAD

**Issue by Leooo** [thoughtbot/ember-cli-rails#407] opened 2016-02-25 00:48 UTC
I'm excited by the ability to use code reload with multi-thread in Rails 5

**Comment by seanpdoyle** [comment] 2016-02-25 02:42
This is a duplicate of https://github.com/thoughtbot/ember-cli-rails/issues/376.

**Closed by seanpdoyle** 2016-02-25 02:42 UTC

**Comment by Leooo** [comment] 2016-02-25 03:27
right sorry
