### ISSUE TITLE
Got "Application has been already initialized." when deploying to Heroku

### ISSUE THREAD

**Issue by dinhhuydh** [thoughtbot/ember-cli-rails#127] opened 2015-03-25 02:25 UTC
Hi,

I installed `ember-1cli-rails` v0.1.13 into my existing Rails 3.2.18 project. It works fine on local host. But when i deployed to Heroku i got the error `Application has been already initialized.`:

Below is the log when deploying to Heroku. I tried to turn off the command `MyApp::Application.initialize!` in `config/environment.rb` but the app crashed on Heroku although it deployed successfully. Do you have any clue why it is and how can i resolve it?

```
-----> Fetching custom git buildpack... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs
=====> Detected Framework: Node.js

-----> Reading application state
       package.json...
       build directory...
       cache directory...
       environment variables...

       Node engine:         unspecified
       Npm engine:          unspecified
       Start mechanism:     Procfile
       node_modules source: package.json
       node_modules cached: true
                                                                                                                                                                        [473/1934]
       NPM_CONFIG_PRODUCTION=true
       NODE_MODULES_CACHE=true

-----> Installing binaries
       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 0.12.0...
       Using default npm version: 2.5.1

-----> Building dependencies
       Restoring node modules from cache
       Pruning unused dependencies
       npm WARN package.json @ No repository field.
       valid
       Installing node modules
       npm WARN package.json @ No repository field.

-----> Checking startup method
       Found Procfile

-----> Finalizing build
       Creating runtime environment
       Exporting binary paths
       Cleaning npm artifacts
       Cleaning previous cache
       Caching results for future builds

-----> Build succeeded!

       @ /tmp/build_8236fbf22ea851f11d6bc9907fbd15eb
       └── bower@1.3.12

       WARNING: Node version not specified in package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby
=====> Detected Framework: Ruby
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-1.9.3
-----> Installing dependencies using 1.7.12
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Using aasm 3.0.23
       Using rake 10.3.2
       Using abn 2.0.0
       Using i18n 0.6.11
       Using multi_json 1.10.1
       Using builder 3.0.4
       Using journey 1.0.4
       Using erubis 2.7.0
.......
      Using tinymce-rails 3.5.8 from git://github.com/spohlenz/tinymce-rails.git (at update-manifest)                                                                  [252/1934]
       Your bundle is complete!
       Gems in the groups development and test were not installed.
       It was installed into ./vendor/bundle
       Bundle completed (1.49s)
       Cleaning up the bundler cache.
-----> Writing config/database.yml to read from DATABASE_URL
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       Connecting to database specified by DATABASE_URL
       Creating scope :from. Overwriting existing method TimesheetEntry.from.
       Creating scope :public. Overwriting existing method ReviewTemplateAnswer.public.
       npm WARN engine makeerror@1.0.10: wanted: {"node":"0.6.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
       npm WARN engine tmpl@1.0.3: wanted: {"node":"0.6.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
       > frontend@0.0.0 postinstall /tmp/build_8236fbf22ea851f11d6bc9907fbd15eb/frontend
       > node_modules/bower/bin/bower install
       bower loader.js#3.2.0       not-cached git://github.com/ember-cli/loader.js.git#3.2.0
       bower loader.js#3.2.0          resolve git://github.com/ember-cli/loader.js.git#3.2.0
       bower ember-cli-shims#0.0.3 not-cached git://github.com/ember-cli/ember-cli-shims.git#0.0.3
       bower ember-cli-shims#0.0.3    resolve git://github.com/ember-cli/ember-cli-shims.git#0.0.3
...

 ├── p-throttler@0.1.0 (q@0.9.7)                                                                                                                                   [27/1934]
       ├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
       ├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.4)
       ├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
       ├── decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-stream@1.1.13, binary@0.3.0)
       ├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
       ├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, no
de-uuid@1.4.3, mime-types@1.0.2, bl@0.9.4, form-data@0.1.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
       ├── bower-registry-client@0.2.4 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
       ├── cardinal@0.4.0 (redeyed@0.4.4)
       ├── mout@0.9.1
       ├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-version@0.2.0, configstore@0.3.2)
       ├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
       ├── inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, lodash@2.4.1, cli-color@0.3.3, rx@2.4.6)
       └── insight@0.4.3 (object-assign@1.0.0, chalk@0.5.1, async@0.9.0, os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0, lodash.debounce@2.4.1)
       The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/tmp/build_8236fbf22ea851f11d6bc9907fbd15eb/frontend/node_mo
dules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
       version: 0.2.0
       Could not find watchman, falling back to NodeWatcher for file system events
Building.Building..Built project successfully. Stored in "/tmp/build_8236fbf22ea851f11d6bc9907fbd15eb/tmp/ember-cli-3ee94d7f-918c-4612-abe1-386e790dac98/apps/front[6/1934]
       ** [Airbrake] Notice was not sent due to configuration:
       Environment Monitored? true
       API key set? false
       rake aborted!
       Application has been already initialized.
       /tmp/build_8236fbf22ea851f11d6bc9907fbd15eb/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/application.rb:135:in `initialize!'
       /tmp/build_8236fbf22ea851f11d6bc9907fbd15eb/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/sprockets/assets.rake:95:in `block (2 levels) in <top (required)>'
       /tmp/build_8236fbf22ea851f11d6bc9907fbd15eb/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
       /tmp/build_8236fbf22ea851f11d6bc9907fbd15eb/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/sprockets/assets.rake:23:in `invoke_or_reboot_rake_task'
       /tmp/build_8236fbf22ea851f11d6bc9907fbd15eb/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.18/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
       Tasks: TOP => assets:precompile:primary => assets:environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !

 !     Push rejected, failed to compile Multipack app
```

**Comment by jamescgibson** [comment] 2015-03-27 18:09
If you don't have ember-cli-rails, is that "API key set? false" line still there? Not an expert, but that's what stands out to me.

**Comment by rwz** [comment] 2015-04-03 21:14
That's weird. I've never seen this one before. Is there a way you could provide a test repo reproducing the error?

**Comment by pedantix** [comment] 2015-04-14 03:57
@jamescgibson that looks like the message from Airbrake gem

**Comment by 2468ben** [comment] 2015-04-29 21:25
Same problem for me. No Airbrake, but using Unicorn and deploying to staging, if that's at all relevant. Is there anything special I should do to make sure staging works? I'm already including `config.consider_all_requests_local = false`.

```
remote:        Building.Building..Building...BuildingBuilding.Built project successfully. Stored in "/tmp/build_71838f14ea40c623517148479022613e/tmp/ember-cli-24bef7dd-b6c1-4aae-a86e-e2f71eb52151/apps/dashboard".
remote:        rake aborted!
remote:        Application has been already initialized.
remote:        /tmp/build_71838f14ea40c623517148479022613e/vendor/bundle/ruby/1.9.1/gems/railties-3.2.18/lib/rails/application.rb:135:in `initialize!'
remote:        /tmp/build_71838f14ea40c623517148479022613e/vendor/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.6/lib/turbo-sprockets/tasks/assets.rake:186:in `block (2 levels) in <top (required)>'
remote:        /tmp/build_71838f14ea40c623517148479022613e/vendor/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.6/lib/turbo-sprockets/tasks/assets.rake:35:in `invoke_or_reboot_rake_task'
remote:        /tmp/build_71838f14ea40c623517148479022613e/vendor/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.6/lib/turbo-sprockets/tasks/assets.rake:50:in `block (2 levels) in <top (required)>'
remote:        Tasks: TOP => assets:precompile:all => assets:cache:clean => assets:environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:
remote:  !     Push rejected, failed to compile Multipack app
```

**Comment by skylar** [comment] 2015-06-29 08:23
I have a similar error too (no Airbrake error on mine):

```
remote:        rake aborted!
remote:        Application has been already initialized.
remote:        /tmp/build_f2a2aab09aa82f21ebfa9bad42457f6e/lib/extensions/object.rb:10:in `raise'
remote:        /tmp/build_f2a2aab09aa82f21ebfa9bad42457f6e/vendor/bundle/ruby/2.1.0/gems/railties-3.2.18/lib/rails/application.rb:135:in `initialize!'
remote:        /tmp/build_f2a2aab09aa82f21ebfa9bad42457f6e/vendor/bundle/ruby/2.1.0/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/tasks/assets.rake:192:in `block (2 levels) in <top (required)>'
remote:        /tmp/build_f2a2aab09aa82f21ebfa9bad42457f6e/vendor/bundle/ruby/2.1.0/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/tasks/assets.rake:35:in `invoke_or_reboot_rake_task'
remote:        /tmp/build_f2a2aab09aa82f21ebfa9bad42457f6e/vendor/bundle/ruby/2.1.0/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/tasks/assets.rake:50:in `block (2 levels) in <top (required)>'
remote:        Tasks: TOP => assets:precompile:all => assets:cache:clean => assets:environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
```

**Comment by skylar** [comment] 2015-06-29 13:14
@rwz here's a repo which captures the unique parts of my setup using a base ember-cli/rails setup.

  https://github.com/skylar/ecli-deploy

Starting at commit 7fe81a5 you'll see the error reproduced on deploy. I'm working on isolating the exact cause. It appears it may be related to initialization in the `dm-rails` gem or related DataMapper setup.

**Comment by skylar** [comment] 2015-06-29 13:29
Isolating the cause, it appears that setting

`config.assets.initialize_on_precompile = false`

triggers the failure. It might be somewhat common for Heroku users since they recommend this in their docs as a way to avoid deploy errors and save time.  I'm sure that's why I set it.

https://devcenter.heroku.com/articles/rails-asset-pipeline#troubleshooting

**Comment by seanpdoyle** [comment] 2015-10-23 19:08
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

Thanks for your patience.

**Closed by seanpdoyle** 2015-10-23 19:08 UTC
