### ISSUE TITLE
ember-welcome-page doesnt work with ember-cli-rails

### ISSUE THREAD

**Issue by salmanasiddiqui** [thoughtbot/ember-cli-rails#495] opened 2016-10-12 09:29 UTC
**Which operating system and version is the project developed on?**
Ubuntu 16.04

**Which version of [`ruby`](https://www.ruby-lang.org/) is the project developed on?**
2.3.1

**Which version of [`npm`](https://www.npmjs.com/) is the project developed on?**
2.15.9

**Which version of [`ember-cli`](http://ember-cli.com/) is the project developed on?**
2.8

**What is the [`rails`](https://github.com/rails/rails) version?**
5.0.0.1

**What is the [`ember-cli-rails`](https://github.com/thoughtbot/ember-cli-rails) version (from `Gemfile`)?**
0.8.1

**What is the [`ember-cli-rails-addon`](https://github.com/rondale-sc/ember-cli-rails-addon/) version (from `package.json`)?**
0.8.0

**Is your application server [multi-threaded](https://github.com/thoughtbot/ember-cli-rails/commit/ef0a49546a8c2e5fb0a298ba455fba97289065a1) (such as `puma` and `unicorn`) or is
it multi-process (such as thin and webrick)?**
multi-threaded (puma)

**What are the contents of `config/initializers/ember.rb`?**

```
EmberCli.configure do |c|
  c.app :frontend
end
```

**What are the contents of the Rails' view that renders the Ember application?**
Its rails 5 api app, there is no rails view.

**How are the EmberCLI-related routes defined?**
`mount_ember_app :frontend, to: '/'`

**How is the application deployed?**
Issue on my local env

I initialized ember project, run `rails server` and visited `localhost:3000`, a blank page was displayed. I visited `localhost:3000/tests` and that displayed a blank page aswell.

But if I run `ember server` within frontend directory and visit `localhost:4200` a welcome page is displayed. And visiting `localhost:4200/tests` displays ember test results.

Does this mean that some ember addons might not work with `ember-cli-rails`?

**Comment by nruth** [comment] 2016-10-25 00:07
I don't think so, because it looks like it's not an ember addon, nor part of your ember application. It doesn't seem reasonable for ember-cli-rails to support it, because it's a deployment solution more than a development server – which ember-cli provides already.

If you explore https://github.com/ember-cli/ember-welcome-page you won't find many files that aren't project boilerplate. The main one seems to be https://github.com/ember-cli/ember-welcome-page/blob/master/index.js and [the commit history shows it used to be express js](https://github.com/ember-cli/ember-welcome-page/commit/00c0a2b568abd352456a0d5267e7a3053e9a69fe).

It looks like that page/addon is a simple webserver (think express.js or sinatra) rather than part of your ember app. It probably only works if you're running the `ember s` development server, and haven't started writing your app yet. ember-cli-rails is a deployment solution more than a development solution, so I wouldn't be surprised if this doesn't get supported.

**Comment by locks** [comment] 2016-11-08 06:37
v1 of `ember-welcome-page` is a middleware for the `ember serve` express.js server.
For v2 we instead provide a component that is to be included in the default `application.hbs` blueprint, so this issue will be solved whenever Ember CLI bumps `ember-welcome-page` to v2.

**Comment by seanpdoyle** [comment] 2016-12-16 16:16
According to https://github.com/thoughtbot/ember-cli-rails/issues/495#issuecomment-259057965, the issue is with the [`ember-welcome-page`](https://github.com/ember-cli/ember-welcome-page) repository.

@salmanasiddiqui do you consider this issue resolved?

I'll close this issue for now. If you think it should be re-opened, please say so.

**Closed by seanpdoyle** 2016-12-16 16:16 UTC
