### ISSUE TITLE
No route matches [GET] "/stylesheets/frontend/vendor.css"

### ISSUE THREAD

**Issue by kgish** [thoughtbot/ember-cli-rails#204] opened 2015-08-30 15:55 UTC
I've followed the instructions for installing the `ember-cli-rails` addon and repeated it a number of times, yet I cannot for the life of me get it to work properly.

Here's what my setup looks like (right out of the book).
```
# config/initializers/ember.rb
EmberCLI.configure do |c|
  c.app :frontend,
    path: '/home/kiffin/projects/na-holland/na-holland-ember'
end
```
In `routes.rb` I added the line:
```
root 'application#index'
```
and
```
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    render :index
  end
end
```
and
```
<!-- app/views/application/index.html.erb -->

<%= include_ember_script_tags :frontend %>
<%= include_ember_stylesheet_tags :frontend %>
```
In my index view I have the following which are generated:
```
<!-- app/views/application/index.html.erb -->

<script src="/javascripts/frontend/vendor.js"></script>
<script src="/javascripts/frontend/na-holland-ember.js"></script>
<link rel="stylesheet" media="screen" href="/stylesheets/frontend/vendor.css" />
<link rel="stylesheet" media="screen" href="/stylesheets/frontend/na-holland-ember.css" />
```
However, when I navigate to the root, for each of these files I'm getting this error message:
```
Started GET "/stylesheets/frontend/vendor.css" for 127.0.0.1 at 2015-08-30 17:46:52 +0200

ActionController::RoutingError (No route matches [GET] "/stylesheets/frontend/vendor.css"):
```
If I run the backend and the front-end separately, `rails server` and `ember server --proxy http://localhost:3000` respectively, everything works just fine.

What am I doing wrong?!

**Comment by straydogstudio** [comment] 2015-08-31 00:26
Looks like this issue: https://github.com/rwz/ember-cli-rails/issues/120

**Comment by mikekellyio** [comment] 2015-09-17 04:05
I am also running into this issue. In addition I'm getting the below:
``ActionController::RoutingError (No route matches [GET] "/javascripts/frontend/frontend.js"):``

I followed the instructions on the Readme and the only difference to @kgish 's setup is in:
```
# config/initializers/ember.rb
EmberCLI.configure do |c|
  c.app :frontend, path: Rails.root.join('frontend').to_s
end
```
I've gotten the error with or without the ``path`` argument.

```
$ ember -v
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: darwin x64
```

```
# Gemfile.lock
# <snip>
ember-cli-rails (0.3.5)
```

**Comment by mikekellyio** [comment] 2015-09-17 12:01
As an update, I tried running ``ember serve`` and that works and loads fine. The problem seems to be somewhere in the ``ember-cli-rails`` integration.

**Comment by seanpdoyle** [comment] 2015-10-23 19:02
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue, as it's a duplicate of https://github.com/thoughtbot/ember-cli-rails/issues/120. If what you've described is still a problem and you think it's unrelated to #120, please comment on this issue and we'll reopen.

Thanks for your patience.

**Closed by seanpdoyle** 2015-10-23 19:02 UTC
