### ISSUE TITLE
symlink getting clobbered on template file changes

### ISSUE THREAD

**Issue by dchersey** [thoughtbot/ember-cli-rails#301] opened 2015-11-23 20:46 UTC
I've been getting intermittent errors when I save a modified .hbs or .js in my ember-cli app (called :ui).

```
:ui has failed to build: Error: ENOENT: no such file or directory, symlink '/Users/david/projects/ia/ui/app' -> '/Users/david/projects/ia/ui/tmp/funnel-input_base_path-9XD7muPD.tmp/0'

    at Error (native)

    at Object.fs.symlinkSync (fs.js:902:18)

    at symlink (ui/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:82:14)

    at symlinkOrCopySync (ui/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)

    at ui/node_modules/ember-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/read_compat.js:58:9

    at lib$rsvp$$internal$$tryCatch (ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)

    at lib$rsvp$$internal$$invokeCallback (ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)

    at lib$rsvp$$internal$$publish (ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)

    at lib$rsvp$asap$$flush (ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

    at doNTCallback0 (node.js:417:9)
```

I tried configuring live-reload with guard-livereload and rack-livereload and this did not help.
I also ensured my puma server is running only 1 thread and this did not help
```
[94149] Puma starting in cluster mode...
[94149] * Version 2.15.3 (ruby 2.2.2-p95), codename: Autumn Arbor Airbrush
[94149] * Min threads: 1, max threads: 1
[94149] * Environment: development
[94149] * Process workers: 1
[94149] * Phased restart available
```
I tried booting with WEBrick; same error. 

I was not getting these errors when I was running ember-cli outside of rails. I will try that separately as a test to rule out other problems. 

Have you seen this before, and what would you suggest I do to troubleshoot?

Deleting the ui/tmp directory, or restarting the rails server fixes the problem temporarily, until I make more changes. Seems to happen every 3 changes or so.

I'm running ember-cli 1.3.8, ember-cli-rails 0.5.1 (with matching ember addon).

**Comment by seanpdoyle** [comment] 2015-11-24 13:49
@dchersey thanks for opening this issue!

Looking at that stack trace, I don't see `ember-cli-rails-addon` anywhere, so it's hard for me to deduce the cause.

EmberCLI `1.3.8` is a few minor versions behind [the latest](https://github.com/ember-cli/ember-cli/releases/latest).

We state in our [README](https://github.com/thoughtbot/ember-cli-rails/blob/master/README.md#ember-cli-rails):

> EmberCLI-Rails Supports EmberCLI 1.13.x and later.

Is upgrading `ember-cli` for your project a possibility? If so please give that a shot.

If you're able to upgrade and it's still a problem, I'll gladly reopen this issue.

**Comment by dchersey** [comment] 2015-11-24 15:18
Sorry -- typo -- I am running ember-cli 1.13.8!  

I agree this is tough because the problem is definitely coming from the ember-cli build. However I have think it is the handling of the symlinks within ember-cli that is causing the issue ... ember is rebuilding an the browser is out of date. Still trying to isolate this by removing dependencies on the sprockets pipeline so I can test it independently.

**Comment by seanpdoyle** [comment] 2015-11-24 15:20
@dchersey I still recommend [upgrading to the latest ember-cli](https://github.com/ember-cli/ember-cli/releases/latest) version.

If you're able to do that and still have an issue, I'll gladly reopen.

**Comment by seanpdoyle** [comment] 2015-11-24 15:24
FWIW, we only [symlink your Ember app's `dist/` to a Sprockets-compatible directory](https://github.com/thoughtbot/ember-cli-rails/blob/41dee1cafc8bee61462a2aa858d891df2f6e6613/lib/ember_cli/app.rb#L102)

Your stack trace:

```
'/Users/david/projects/ia/ui/app' -> '/Users/david/projects/ia/ui/tmp/funnel-input_base_path-9XD7muPD.tmp/0'
```

doesn't seem to involve the source (your Ember App's `dist/` directory ) or the destination (Rails' `tmp/ember-cli-$SOME-HASH/assets`) of the symlink

**Comment by dchersey** [comment] 2015-11-24 17:08
Ok, updated to ember-cli 1.13.13 and issue still remains. Regarding the symlink location, that is very strange. I am not in control of the ember build, but it appears to not be using dist? Is the source of the symlink correct (does ember-cli-rails symlink my ember-app's app directory to the dist directory or sprockets destination?)  Where is this configured?  My ember.rb initializer simply says 

```ruby
EmberCli.configure do |c|
  c.app :ui
end
```

**Comment by dchersey** [comment] 2015-11-24 18:04
more info: 

after a successful build initiated via ember-cli-rails, I see that I have directories in my-rails-app/tmp as follows: 

```
drwxr-xr-x  4 david  staff  136 Nov 24 12:51 ember-cli-a0b22d7c-93f9-4506-a4c3-35704318c819
drwxr-xr-x  4 david  staff  136 Nov 24 12:31 ember-cli-a27099eb-5850-490b-a06b-606143da78c7
drwxr-xr-x  4 david  staff  136 Nov 23 16:03 ember-cli-d36a9fde-ff45-423f-bbfd-8afe58ad9080
```
Note that they are 20 minutes apart.  Within each of these (say the latest) I see a structure that looks like

```
apps   assets

./apps:
ui

./apps/ui:
assets          crossdomain.xml index.html      robots.txt      testem.js       tests

./apps/ui/assets:
bootstrap.css.map index.html        test-support.css  tests.js          ui.js             vendor.js
ember-data.js.map passed.png        test-support.js   tests.map         ui.map            vendor.map
failed.png        test-loader.js    test-support.map  ui.css            vendor.css

./apps/ui/tests:
index.html

./assets:
ui
```

the final ./assets/ui is symlinked to the ./apps/ui. At no point is the `ui/dist` directory symlinked; it appears ember-cli-rails is being told to build to `my-rails-app/tmp/ember-cli<hash>/apps/ui` and that resulting stuff is symlinked user ./assets/ui .

This makes sense because of support for multiple apps -- I only have one called ui.

This all works great -- the only problem seems to be that sometimes (why?) the hash changes, and the whole mess gets replicated. When that happens the browser and server are clueless; I have to restart the server to get catch it up.

**Comment by seanpdoyle** [comment] 2015-11-25 00:04
@dchersey thanks for the additional information!

We've just landed a change that alters the way the process cleans up old builds:

https://github.com/thoughtbot/ember-cli-rails/commit/2d51daa8cbcd51d24bf94f6d509c476cbdafc5fe

Could you pull that down and give it a shot?

**Comment by dchersey** [comment] 2015-11-25 17:52
It is a little weird ... I pulled this down and ran it, and it is showing me an out of date version of my app. 
I have tried `rake cache:clean`, deleted ui/dist, ui/tmp, tmp, public/assets and everything and it keeps rendering an old version. 

I no longer see the building... message in the log, but I do see it creating tmp/ember-cli-<hash> directories and when I look in there I do see the changed HTML being rendered by apps/ui/assets/ui.js. 

When I render my ember view, using a custom controller and layout that renders 
```
<%= render_ember_app :ui do |head| %>
  <% head.append do %>

    <%= csrf_meta_tags %>

  <% end %>
<% end %>
```
I do not see my changes. 

If i start ember serve in my ui directory, I do see them. 

Frankly I can't figure out where the browser is getting the old stuff from.  Continuing to work on it ...

**Comment by dchersey** [comment] 2015-11-25 18:07
Ok, fell back to the released gem and still having trouble. I brought in some new configs to my ember app last night; I will see if I can rewind and get things back to where they were then update to this new build; stay tuned.

**Comment by dchersey** [comment] 2015-11-25 19:10
Removing previous comments so I can consolidate here: 

I reverted to an earlier commit before playing with this change, and in the process broke some things about how my app works. In troubleshooting that, I removed the guard-livereload gem, rack-livereload, and my browser extension.  

I can no longer reproduce the original problem using the released version of the gem. 

I am about to try the new commit above, then try bringing in the live-reload stuff again carefully. Perhaps in the process I will re-encounter the issue, or perhaps not.  Either outcome would probably be useful so I will let you know.

**Comment by dchersey** [comment] 2015-11-25 19:31
Ok, I updated the gem to commit 2d51daa and I did NOT have the problem. So far so good. 
I added guard-livereload and rack-livereload and when I update a file, I see guard initiate a live-reload and the rails server (puma) tells me 
```
ActionController::RoutingError (No route matches [GET] "/assets/ui/assets/vendor.js"):
  vendor/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
  vendor/ruby/2.2.0/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  vendor/ruby/2.2.0/gems/request_store-1.2.1/lib/request_store/middleware.rb:8:in `call'
  vendor/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
  vendor/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/ruby/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
  vendor/ruby/2.2.0/gems/airbrake-3.2.1/lib/airbrake/user_informer.rb:16:in `_call'
  vendor/ruby/2.2.0/gems/airbrake-3.2.1/lib/airbrake/user_informer.rb:12:in `call'
  vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
  vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
  vendor/ruby/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
  vendor/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  vendor/ruby/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
  vendor/ruby/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
  vendor/ruby/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
  vendor/ruby/2.2.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
  vendor/ruby/2.2.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

That's new, and possibly due to the above changes?  Anyway it's looking like live-reload could be the issue. I will try it without rack-livereload and see if it happens with the browser extensions.

**Comment by dchersey** [comment] 2015-11-25 19:38
Scratch that previous comment. I had not properly inserted the rack-livereload middleware in my environment.rb.

It is working now ... live-reloading and no errors so far.  Will let you know if that changes. 

And THANKS for all your help; this has been a sticky one to chase down for some reason.

**Comment by seanpdoyle** [comment] 2015-11-25 20:13
@dchersey that's great news!

Thanks for tracking this down. I'll close this for now.

**Closed by seanpdoyle** 2015-11-25 20:13 UTC
