### ISSUE TITLE
Is there a happy path to making http-mocks work?

### ISSUE THREAD

**Issue by ryanere** [thoughtbot/ember-cli-rails#128] opened 2015-03-25 16:51 UTC
First off, great job on this gem!  The setup was seamless and I was up and running in minutes.

I was wondering if anyone had a suggestion of how to get http-mocks to place nicely with ember-cli-rails?   I have a catch-all route in Rails so that I can use Ember router with historyLocation and as expected it's catching all of the requests I'd like to be hitting the http-mock server.

**Comment by rwz** [comment] 2015-04-03 21:13
I don't quite get it. What exactly do you mean by http-mocks? Could you elaborate?

**Comment by chrisdpeters** [comment] 2015-04-30 00:53
You can find out more about http-mocks here:
http://cball.me/talk/real-world-fixtures/

**Comment by jozefvaclavik** [comment] 2015-06-03 13:42
@rwz http-mocks are used for development and/or testing http://www.ember-cli.com/#mocks-and-fixtures the problem is that `Note: Mocks are just for development and testing. The entire /server directory will be ignored during ember build.` and because ember-cli-rails uses build command, all requests are served directly to API instead to available mocks.. while this is kind of fine for development, but not for testing..

**Comment by seanpdoyle** [comment] 2015-10-23 19:08
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue. If what you've described is still a problem, please comment on this issue and we'll reopen.

I've personally never used `http-mocks`, but I *have* used [ember-cli-mirage](https://github.com/samselikoff/ember-cli-mirage), and I would recommend checking it out. 

Thanks for your patience.

**Closed by seanpdoyle** 2015-10-23 19:08 UTC

**Comment by jozefvaclavik** [comment] 2015-10-24 07:30
mirage FTW! we switched there as well. everyone is using it. lol.

**Comment by ryanere** [comment] 2015-10-24 07:33
:+1: Thanks guys.
