### ISSUE TITLE
How to load javascript assets?

### ISSUE THREAD

**Issue by mehulkar** [thoughtbot/ember-cli-rails#162] opened 2015-05-01 06:40 UTC
I followed the README and attempted to get an ember-cli app bootstrapped into an existing Rails 4 app. I did the following:

1. installed the gem
1. initialized the app in the `:rails_root/onboard` directory
1. added the rails initializer with the path and the name "onboard"
1. Added a `get /onboard` route to the Rails app
1. Added an `OnboardController` that renders a html.erb file
1. Added the include tags (`<%= stylesheet_link_tag 'onboard' %>` for css and `<%= include_ember_script_tags :onboard %>` for js in the view that is rendered (didn't bother with layout files.
1. Added a stylesheet file at  `app/assets/stylesheets/onboard.css`

When I load the page, I get the following 404s:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/javascripts/onboard/onboard.js
Failed to load resource: the server responded with a status of 404 (Not Found)
```

I can see that it's looking for the js files there, but I don't understand if the gem is supposed to load those dynamically? Or am I supposed to add the compiled build at that path? The README doesn't really address this as far as I can tell (or maybe I'm missing  it). 

In either case, opening this up as a documentation issue (happy to contribute once I get the issue sorted out), because it seems like other people have this working fine. 

Thanks! The setup was much much smoother than I expected it to be, just one last hurdle!

**Comment by mehulkar** [comment] 2015-05-01 06:46
Hmm, looks like #120 is related (or maybe the same) problem.

**Comment by mehulkar** [comment] 2015-05-01 06:52
Also looks like the assets are loaded by a symlinking strategy from ember-cli app's `tmp` dir and a dir in rails tmp dir. So it looks like in my case, that symlinking is not happening.

**Comment by rondale-sc** [comment] 2015-05-01 13:17
@mehulkar So ember-cli-rails should put those built assets into the asset path.  

Could you check and see if you are in your `onboard` ember cli app that you can `ember build` successfully.  

That you have the npm addon installed in `onboard` 

And also let me know the versions of all the stuff you are using.  EmberCLI, node, npm, etc.  Thanks!

**Comment by mehulkar** [comment] 2015-05-04 16:21
@rondale-sc I successfully ran `ember build`. Here's some version info:

```bash
$ cat Gemfile.lock | grep ember-cli
    ember-cli-rails (0.3.1)

$ cat onboard/package.json | grep rails
    "ember-cli-rails-addon": "0.0.11",

$ cat onboard/package.json | grep ember-cli
    "ember-cli": "0.2.3",

$ node -v
v0.10.33

$ npm -v
1.8.4
```

**Comment by craigmcnamara** [comment] 2015-05-06 23:05
I was having this problem and adding `config.middleware.use EmberCLI::Middleware` to `config/application.rb` fixed the issue. I'm running Rails 4.2.0

**Comment by mehulkar** [comment] 2015-05-08 00:04
@craigmcnamara tried that on Rails 4.1.1 and it did not fix the issue. But that gives me some good direction to start debugging.

**Comment by neilor** [comment] 2015-05-13 03:02
@craigmcnamara, its fixed my issue too. I'm running Rails 4.2.0.

@rondale-sc, are you using `gem 'rack-cors'`? Try to remove and replace middleware like @craigmcnamara says.

**Comment by aidewoode** [comment] 2015-06-09 15:55
I think I have same issue too. When I first time start the rails server, then I go to localhost:3000, and the web console show some 404 errors. And the page was blank ,till when I refreshed the page , the page finally show the right thing. It's so weird.

![2015-06-09 11 46 37](https://cloud.githubusercontent.com/assets/6188618/8062554/e9f5b9dc-0f02-11e5-9aa2-d6eae76db3c8.png)

**Comment by mehulkar** [comment] 2015-07-01 00:03
Setting the `build_timeout` option to 10 helped with this. i think it's a timing issue for the missing assets. 

```ruby
EmberCLI.configure do |c|
  c.app :frontend, build_timeout: 10
end
```

**Comment by joshpfosi** [comment] 2015-07-26 13:07
I am still experiencing this issue :( None of these suggestions have helped.

**Comment by seanpdoyle** [comment] 2015-10-23 19:00
We're sorry that this issue has sat for so long. 

The project is now maintained by thoughtbot, and we're declaring an issue bankruptcy of sorts.

We're closing this issue, as it's a duplicate of https://github.com/thoughtbot/ember-cli-rails/issues/120. If what you've described is still a problem and you think it's unrelated to #120, please comment on this issue and we'll reopen.

Thanks for your patience.

**Closed by seanpdoyle** 2015-10-23 19:00 UTC
